{{- $application := .Values.applications.web -}}
{{- $service := .Values.services.db -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ip-reverse-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ $application.name }}
  minReplicas: {{ $application.minReplicas }}
  maxReplicas: {{ $application.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metricName: http_requests
      targetAverageValue: {{ $application.autosacleRequestsPerSecond }}