{{- $service := .Values.services.db -}}
{{- $application := .Values.applications.db -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  labels:
    db: {{ $service.name }}
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: {{ $service.type }} 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: {{ $service.port }}
    name: redisdb
    targetPort: 6379
  selector:
    db: {{ $application.name }}